import { defineConfig } from 'astro/config';
import node from '@astrojs/node';
import react from '@astrojs/react';
import tailwind from '@astrojs/tailwind';

// Public canonical origin — used by <Seo>, sitemap, robots, JSON-LD.
const SITE = process.env.PUBLIC_SITE_URL || 'https://shieldvase.io';

export default defineConfig({
  site: SITE,
  output: 'hybrid', // SSG by default, opt-in SSR per page via `export const prerender = false`
  adapter: node({ mode: 'standalone' }),
  integrations: [
    react(),
    tailwind({ applyBaseStyles: false }),
    // NOTE: sitemaps are generated by src/pages/sitemap-*.xml.ts. We do not use
    // the @astrojs/sitemap integration — it crashes when all pages are filtered
    // out and would otherwise emit a conflicting /sitemap.xml.
  ],
  server: { host: '127.0.0.1', port: 4321 },
  build: { inlineStylesheets: 'auto' },
  vite: { ssr: { noExternal: ['@supabase/supabase-js'] } },
});
