import { defineConfig } from 'astro/config';
import node from '@astrojs/node';
import react from '@astrojs/react';
import sitemap from '@astrojs/sitemap';
import tailwind from '@astrojs/tailwind';

// Public canonical origin — used by <Seo>, sitemap, robots, JSON-LD.
const SITE = process.env.PUBLIC_SITE_URL || 'https://shieldvase.io';

export default defineConfig({
  site: SITE,
  output: 'hybrid', // SSG by default, opt-in SSR per page via `export const prerender = false`
  adapter: node({ mode: 'standalone' }),
  integrations: [
    react(),
    tailwind({ applyBaseStyles: false }),
    // NOTE: chunked sitemap is generated by src/pages/sitemap-*.xml.ts.
    // Keep @astrojs/sitemap installed for future use but disable its output
    // so we don't emit a conflicting /sitemap.xml.
    sitemap({ filter: () => false }),
  ],
  server: { host: '127.0.0.1', port: 4321 },
  build: { inlineStylesheets: 'auto' },
  vite: { ssr: { noExternal: ['@supabase/supabase-js'] } },
});
